joy_node:
  ros__parameters:
    dev: "/dev/input/js0"
    deadzone: 0.05
    autorepeat_rate: 20.0
    dev_ff: "/dev/input/event258"

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 0.5


    enable_button: 0
    enable_turbo_button: 10

    require_enable_button: true
